name: Release

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: 'pip' # caching pip dependencies
      - name: Install build dependencies
        run: python -m pip install -U setuptools wheel build twine
      - name: Build
        run: python -m build .
      - name: Verify the distributions
        run: twine check dist/*
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
          skip_existing: true
  publish-sphinx-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: 'pip' # caching pip dependencies
      - name: Install package requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Sphinx
        run: python -m pip install -U sphinx
      - name: Install Sphinx requirements
        run: |
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          sphinx-build -b html ./docs/source ./docs/build/html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
